keys:
  - &host_sid age1ytfze9tv5l80ujqfd66xp97w2u0lq8jrx45ulf0szey8ny0t837sdktdzf
  - &host_rv2 age1j6s2ec3ltm9004fhvmd7xqq0zna2fr4m8kw4f235r9k0hfryjctq050vs2
  - &user_sid age19yeqvv28fgrtk6jsh3xyaf0lch86kna6rcz4dwe962yyyyevu30sx474xy
creation_rules:
  - path_regex: hosts/sid/secrets.yaml$
    key_groups:
    - age:
      - *user_sid
      - *host_sid
  - path_regex: hosts/rv2/secrets.yaml$
    key_groups:
    - age:
      - *user_sid
      - *host_rv2
  - path_regex: users/sid/home/secrets.yaml$
    key_groups:
    - age:
      - *user_sid
